data <- read.csv("input.csv")
print(data)
print(ncol(data))
print(nrow(data))
sal <- max(data$salary)
print(sal)
retval <- subset(data, salary == max(salary))
print(retval)
retval1 <- subset(data, dept == "IT")
print(retval1)
info <- subset(data, salary > 20000 & dept == "IT")
print(info)
write.csv(info, "output.csv", row.names = FALSE)
newdata <- read.csv("output.csv")
print(newdata)
